//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfPcAccounting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int id_History { get; set; }
        public int PC_id { get; set; }
        public string Operation { get; set; }
        public System.DateTime CreateAt { get; set; }
    
        public virtual PC PC { get; set; }
    }
}
