//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfPcAccounting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC_Storage
    {
        public int id_PC_Storage { get; set; }
        public int id_PC { get; set; }
        public int id_Storage { get; set; }
    
        public virtual PC PC { get; set; }
        public virtual Storage Storage { get; set; }
    }
}
