//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfPcAccounting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechnicalSpecifications
    {
        public int ID { get; set; }
        public string PCname { get; set; }
        public string NameMotherboard { get; set; }
        public string NameRAM { get; set; }
        public string NameGPU { get; set; }
        public string NamePower { get; set; }
        public string NameCPU { get; set; }
        public string NameCooler { get; set; }
    }
}
