//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfPcAccounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barcode_Inventory
    {
        public int id_Barcode_Inventory { get; set; }
        public int id_Barcode { get; set; }
        public int id_Inventory { get; set; }
        public int Count { get; set; }
    
        public virtual Barcode Barcode { get; set; }
        public virtual Inventory Inventory { get; set; }
    }
}
