//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfPcAccounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CPU()
        {
            this.Motherboard = new HashSet<Motherboard>();
        }
    
        public int id_CPU { get; set; }
        public string Serial_name { get; set; }
        public int Cores { get; set; }
        public string Frequency { get; set; }
        public int id_Cooler_CPU { get; set; }
        public int id_Socket { get; set; }
    
        public virtual Cooler_CPU Cooler_CPU { get; set; }
        public virtual Socket Socket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Motherboard> Motherboard { get; set; }
    }
}
